import {
  Sprout,
  UserCircle,
  Car,
  HardHat,
  GraduationCap,
  Zap,
  Film,
  Landmark,
  UtensilsCrossed,
  Stethoscope,
  Home,
  Factory,
  Briefcase,
  Package,
  Pickaxe,
  Leaf,
  MoreHorizontal,
  Heart,
  Building2,
  Building,
  ShieldCheck,
  Wrench,
  ShoppingCart,
  Trophy,
  Truck,
} from "lucide-react";

export const categories = [
   {
     name: "Agriculture",
     icon: Sprout,
     color: "bg-emerald-500",
     href: "/category/agriculture",
   },
   {
     name: "Artist/Personality",
     icon: UserCircle,
     color: "bg-pink-500",
     href: "/category/artist",
   },
   {
     name: "Automotive",
     icon: Car,
     color: "bg-blue-500",
     href: "/category/automotive",
   },
   {
     name: "Construction",
     icon: HardHat,
     color: "bg-amber-600",
     href: "/category/construction",
   },
   {
     name: "Education",
     icon: GraduationCap,
     color: "bg-indigo-500",
     href: "/category/education",
   },
   {
     name: "Energy",
     icon: Zap,
     color: "bg-yellow-500",
     href: "/category/energy",
   },
   {
     name: "Entertainment",
     icon: Film,
     color: "bg-purple-500",
     href: "/category/entertainment",
   },
   {
     name: "Finance",
     icon: Landmark,
     color: "bg-green-600",
     href: "/category/finance",
   },
   {
     name: "Food/Hospitality",
     icon: UtensilsCrossed,
     color: "bg-orange-500",
     href: "/category/food",
   },
   {
     name: "Health/Medical",
     icon: Stethoscope,
     color: "bg-red-500",
     href: "/category/health",
   },
   {
     name: "Home & Garden",
     icon: Home,
     color: "bg-lime-600",
     href: "/category/home-garden",
   },
   {
     name: "Industrial",
     icon: Factory,
     color: "bg-slate-600",
     href: "/category/industrial",
   },
   {
     name: "Job Seekers",
     icon: Briefcase,
     color: "bg-sky-600",
     href: "/category/jobs",
   },
   {
     name: "Manufacturing",
     icon: Package,
     color: "bg-teal-600",
     href: "/category/manufacturing",
   },
   {
     name: "Mining",
     icon: Pickaxe,
     color: "bg-stone-700",
     href: "/category/mining",
   },
   {
     name: "Natural Resources",
     icon: Leaf,
     color: "bg-green-500",
     href: "/category/natural-resources",
   },
   {
     name: "Personal Services",
     icon: Heart,
     color: "bg-rose-400",
     href: "/category/personal-services",
   },
   {
     name: "Public Org/Gov",
     icon: Building2,
     color: "bg-blue-700",
     href: "/category/government",
   },
   {
     name: "Real Estate",
     icon: Building,
     color: "bg-violet-600",
     href: "/category/real-estate",
   },
   {
     name: "Safety & Legal",
     icon: ShieldCheck,
     color: "bg-zinc-600",
     href: "/category/safety-legal",
   },
   {
     name: "Services",
     icon: Wrench,
     color: "bg-blue-400",
     href: "/category/services",
   },
   {
     name: "Shopping",
     icon: ShoppingCart,
     color: "bg-pink-600",
     href: "/category/shopping",
   },
   {
     name: "Sport & Training",
     icon: Trophy,
     color: "bg-amber-500",
     href: "/category/sport",
   },
   {
     name: "Transportation",
     icon: Truck,
     color: "bg-orange-600",
     href: "/category/transportation",
   },
   {
     name: "Other",
     icon: MoreHorizontal,
     color: "bg-gray-400",
     href: "/category/other",
   },
 ];